#!/usr/bin/env bash
#This bash script displays 'Best School" 10 times but "Hi" at 9th iteration

count=1
while [ $count -le 10 ];
do
echo "Best School"

#Added condition to display "Hi" on the 9th iteration

if [ $count -eq 9 ];
then
echo "Hi"
fi
((count++))
done
